#!/bin/bash

# Check if it is a laptop

laptop=false
test -d /sys/class/power_supply/BAT1 && laptop=true

echo "LAPTOP: $laptop"

mkdir git

yes | sudo pacman -Syu
sudo pacman -S ttf-font-awesome fzf imagemagick polkit-gnome sway gvim thunar htop cloc grim slurp jq libnotify cmatrix wl-clipboard bash-completion dmenu fastfetch obs-studio imv mpv xorg-xwayland qt6-wayland firefox ncdu git wget curl swaylock swaybg swayidle man-db man-pages pamixer blueman alacritty gcc rust go ttf-jetbrains-mono discord foot zip unzip sl brightnessctl zathura zathura-pdf-mupdf arc-gtk-theme papirus-icon-theme galculator openssh dunst xdg-desktop-portal-wlr

gsettings set org.gnome.desktop.interface gtk-theme "Arc-Dark"
gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"

sudo systemctl enable --now sshd
sudo systemctl enable --now bluetooth

echo '[[ "$(tty)" == "/dev/tty1" ]] && exec sway' >> .bash_profile

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

git clone https://github.com/ianis-belu/vim.git

cp vim/vimrc .vimrc

yes | rm -r vim

echo 'XDG_DESKTOP_DIR="$HOME/desktop"' >> .config/user-dirs.dirs
mkdir desktop
echo 'XDG_DOCUMENTS_DIR="$HOME/documents"' >> .config/user-dirs.dirs
mkdir documents
echo 'XDG_DOWNLOAD_DIR="$HOME/downloads"' >> .config/user-dirs.dirs
mkdir downloads
echo 'XDG_MUSIC_DIR="$HOME/music"' >> .config/user-dirs.dirs
mkdir music
echo 'XDG_PICTURES_DIR="$HOME/pictures"' >> .config/user-dirs.dirs
mkdir pictures
echo 'XDG_PUBLICSHARE_DIR="$HOME/public"' >> .config/user-dirs.dirs
mkdir public
echo 'XDG_TEMPLATES_DIR="$HOME/templates"' >> .config/user-dirs.dirs
mkdir templates
echo 'XDG_VIDEOS_DIR="$HOME/videos"' >> .config/user-dirs.dirs
mkdir videos

mkdir info
mkdir git
mkdir scripts

echo 'export PATH="$HOME/scripts:$PATH"' >> .bashrc
echo 'alias p="sudo pacman"'>> .bashrc
echo 'alias suspend="systemctl suspend"' >> .bashrc

mkdir .config/swaylock
echo 'image="/home/ianis/pictures/wallpapers/default"' > .config/swaylock/config

cd git
git clone https://aur.archlinux.org/yay.git
cd yay
yes | makepkg -si

yes | yay -S tofi

[[ $laptop == true ]] && yes | yay -S auto-cpufreq && sudo systemctl enable --now auto-cpufreq

cd ~

git clone https://github.com/ianis-belu/sway-config.git

mkdir .config/sway
mkdir .config/tofi
mkdir .config/alacritty
cp sway-config/config .config/sway/
cp sway-config/bar scripts/
cp sway-config/tofi .config/tofi/config
cp sway-config/alacritty.toml .config/alacritty/

chmod +x scripts/bar

yes | rm -r sway-config

mkdir pictures/wallpapers
cd pictures/wallpapers
wget https://w.wallhaven.cc/full/2y/wallhaven-2ymp5g.png
cp wallhaven-2ymp5g.png default

cd ~
